bot:
  commands_require_mention: false
  commands_level_getter: commands.command_level_getter
  commands_prefix: '+'
  plugins:
    - commands.announce
    - commands.events
    - commands.experience
    - commands.pager
    - commands.guide
